### ISSUE TITLE
Creating New Model - No Value Defined for Enum

### ISSUE THREAD

**Issue by ibnuhalimm** [spatie/laravel-enum#80]
I have :
- Package model with package_type attribute
- PackageTypeEnum class

I already cast the `package_type` attribute with `PackageTypeEnum` class, it's working properly as expected, but I got an issue while creating new model, unable to assign value directly.
In my views, I loaded the values and labels of `PackageTypeEnum` using `toArray()` static method then make them as select option field. When I try to create new Package it respond an error for package_type field

-  views
```php
<select name="package_type" id="__package_typeAddPackage">
    <option value="" selected disabled>
        {{ __('Select Type') }}
    </option>
    @foreach ($packageTypes as $value => $label)
        <option value="{{ $value }}">
            {{ $label }}
        </option>
    @endforeach
</select>
```

- store method
```php
...
    public function store(StoreRequest $request)
    {
            $data = $request->validated();

            $package = new Package();
            $package->package_type = $data['package_type'];
...
```

- the errors
```
There's no value 2 defined for enum App\Enums\PackageTypeEnum, ...
```

What's the best practice and/or How to deal with this case, when we want to directly assign the value to our Enum cast attributes?
Do I have to create new method that returns every single value of my enum static method?

Thanks

**Comment by Gummibeer** [comment]
Hey,

The message could be misleading in your case. As I assume that the problem is typing.
The request value is a string, but the enum uses integer. So casting the request value to string before it's assigned as model attribute should solve it.

It's a task on my list for hacktoberfest to solve this.

**Comment by ibnuhalimm** [comment]
Hi @Gummibeer 
Thank you for your response.

Yes, your assume is correct.
But when I tried to type my request data to (string), it's still not working. I got same errors.
Any other suggestions?

**Comment by Gummibeer** [comment]
Have you upgraded to [spatie/enum:v3.10.0](https://github.com/spatie/enum/releases/tag/3.10.0)? 🤔
This should solve the string/integer problem.

**Comment by ibnuhalimm** [comment]
Ahaa, it's working well now with spatie/enum v3.10.0
Thank you very much @Gummibeer
